### ISSUE TITLE
Conflicting Conda packages

### ISSUE THREAD

**Issue by aozalevsky** [kalininalab/alphafold_non_docker#1]
First - thanks for the recipe!

During the deployment in the section with dependencies I run into a small problem:

https://github.com/kalininalab/alphafold_non_docker#install-dependencies

```
conda install -y -c anaconda cudnn==8.2.1
conda install -y -c bioconda hmmer hhsuite==3.3.0 kalign2
conda install -y -c conda-forge openmm==7.5.1 cudatoolkit==11.0.3 pdbfixer
```

installation of cudnn already pulls cudatoolkit as a dependency:
```

  added / updated specs:
    - cudnn==8.2.1


The following NEW packages will be INSTALLED:

  cudatoolkit        pkgs/main/linux-64::cudatoolkit-11.3.1-h2bc3f7f_2
  cudnn              pkgs/main/linux-64::cudnn-8.2.1-cuda11.3_0

```

which later conflicts with the 
`conda install -y -c conda-forge openmm==7.5.1 cudatoolkit==11.0.3 pdbfixer`

Seems that the proper way would be to use both cudnn and cudatoolkit from the same repo - conda-forge. I wonder though where the cudnn dependency came from because it is not mentioned in the reference Dockerfile.

**Comment by aozalevsky** [comment]
BTW, just for the sake of completeness, the "Disclaimer" part should also include the actual storage consumption.

**Comment by sanjaysrikakulam** [comment]
Hi @aozalevsky,

Thank you, I will update the readme and change the cudnn's channel to conda-forge. It is actually not specified as a dependency in AlphaFolds docker file, I assume it is packaged in the base docker image that they use, if it is not then the TensorFlow will raise warnings and probably not use GPU at all. TensorFlow's documentation lists cudnn as one of their requirements.

**Comment by sanjaysrikakulam** [comment]
Readme is now updated.
