### ISSUE TITLE
The B-factor field (pLDDT confidence measure) of the output PDB file is always 0 

### ISSUE THREAD

**Issue by Yuangaga** [kalininalab/alphafold_non_docker#11]
Hi~Thanks for your work. And I have run alphafold without docker successfully following your tutorial. But the output PDB file may be something wrong:

The B-factor field, which is stored pLDDT confidence measure, of the output PDB file is always 0 in my test work based on the example query.fasta.

![WechatIMG281](https://user-images.githubusercontent.com/42559961/129520474-0032c759-1966-4abf-8017-bd3475c12375.jpeg)

<img width="1396" alt="截屏2021-08-16 下午2 31 34" src="https://user-images.githubusercontent.com/42559961/129520703-dbc45816-c95d-491e-852a-380b511b831f.png">

 And I saw the same result in your dummy_test/query/anked_0.pdb. 
![WechatIMG282](https://user-images.githubusercontent.com/42559961/129520613-8d645e50-7225-47b5-9511-7bcf56ebd789.jpeg)

Then I tried to use the AlphaFold Colab notebook demo for validation. The result from AlphaFold Colab notebook seems no problem. 

![WechatIMG283](https://user-images.githubusercontent.com/42559961/129522005-526d349c-45c4-46c0-931c-19c654159d7b.jpeg)

<img width="1460" alt="截屏2021-08-16 下午2 41 42" src="https://user-images.githubusercontent.com/42559961/129522033-98bd4006-d96f-40a0-a4d4-fe0d1a299d23.png">

So is there any way to fix it ?
Thanks a lot.

**Comment by sanjaysrikakulam** [comment]
Hi @Yuangaga 

Sorry, our non-docker version is only a wrapper script to run AF2. Unlike the colab variant, we do not directly work with the AF2 codebase in the non-docker version. Maybe raise a ticket in the AF2 github repo and they can add the feature to their codebase.

**Comment by sanjaysrikakulam** [comment]
Hi @Yuangaga

Seems like AF2 has recently added this [feature](https://github.com/deepmind/alphafold/commit/cef198e0b650bf35431419db1d91d6aedac75e82) to add the B-factors to the PDB file. So, can you try it by pulling the latest version of AF2?

**Comment by Yuangaga** [comment]
Oh, I see it. Thank you very much. I will try it.

**Comment by Yuangaga** [comment]
> Hi @Yuangaga
> 
> Seems like AF2 has recently added this [feature](https://github.com/deepmind/alphafold/commit/cef198e0b650bf35431419db1d91d6aedac75e82) to add the B-factors to the PDB file. So, can you try it by pulling the latest version of AF2?

Thanks! It worked.
