### ISSUE TITLE
HHblits failed

### ISSUE THREAD

**Issue by lugoly** [kalininalab/alphafold_non_docker#14]
Who could do me a favor? 
when I run AF2, came up with HHblits error.
script:
**python ./run_alphafold.py --fasta_paths=XXX.fas**

results:
/home/linlab/.local/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --output_dir has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/home/linlab/.local/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --model_names has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/home/linlab/.local/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --data_dir has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/home/linlab/.local/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --preset has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/home/linlab/.local/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --uniref90_database_path has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/home/linlab/.local/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --mgnify_database_path has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/home/linlab/.local/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --uniclust30_database_path has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/home/linlab/.local/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --bfd_database_path has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/home/linlab/.local/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --pdb70_database_path has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/home/linlab/.local/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --template_mmcif_dir has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/home/linlab/.local/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --max_template_date has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
/home/linlab/.local/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --obsolete_pdbs_path has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
I0827 14:21:24.269093 140066848117952 templates.py:880] Using precomputed obsolete pdbs /data1/AF2_Database/pdb_mmcif/obsolete.dat.
I0827 14:21:26.650146 140066848117952 xla_bridge.py:236] Unable to initialize backend 'tpu_driver': Not found: Unable to find driver in registry given worker: 
I0827 14:21:27.050851 140066848117952 xla_bridge.py:236] Unable to initialize backend 'tpu': Invalid argument: TpuPlatform is not available.
I0827 14:21:38.779491 140066848117952 run_alphafold.py:293] Have 5 models: ['model_1', 'model_2', 'model_3', 'model_4', 'model_5']
I0827 14:21:38.779775 140066848117952 run_alphafold.py:306] Using random seed 8466485706823161682 for the data pipeline
I0827 14:21:38.780414 140066848117952 pipeline.py:130] query uniref90
I0827 14:21:38.780694 140066848117952 jackhmmer.py:119] Launching subprocess "jackhmmer -o /dev/null -A /tmp/tmpng40rd11/output.sto --noali --F1 0.0005 --F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --cpu 8 -N 1 GARS_insertion.fas /data1/AF2_Database/uniref90/uniref90.fasta"
I0827 14:21:38.840389 140066848117952 utils.py:36] Started Jackhmmer (uniref90.fasta) query
I0827 14:28:35.052657 140066848117952 utils.py:40] Finished Jackhmmer (uniref90.fasta) query in 416.212 seconds
I0827 14:28:35.053834 140066848117952 pipeline.py:141] query mgnify
I0827 14:28:35.054065 140066848117952 jackhmmer.py:119] Launching subprocess "jackhmmer -o /dev/null -A /tmp/tmp48u78l3n/output.sto --noali --F1 0.0005 --F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --cpu 8 -N 1 GARS_insertion.fas /data1/AF2_Database/mgnify/mgy_clusters.fa"
I0827 14:28:35.103244 140066848117952 utils.py:36] Started Jackhmmer (mgy_clusters.fa) query
I0827 14:36:06.724052 140066848117952 utils.py:40] Finished Jackhmmer (mgy_clusters.fa) query in 451.621 seconds
I0827 14:36:06.727063 140066848117952 pipeline.py:153] query mgnify
I0827 14:36:06.727788 140066848117952 hhblits.py:128] Launching subprocess "hhblits -i GARS_insertion.fas -cpu 4 -oa3m /tmp/tmptyl5pi44/output.a3m -o /dev/null -n 3 -e 0.001 -maxseq 1000000 -realign_max 100000 -maxfilt 100000 -min_prefilter_hits 1000 -d /data1/AF2_Database/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt -d /data1/AF2_Database/uniclust30/uniclust30_2018_08/uniclust30_2018_08"
I0827 14:36:06.858779 140066848117952 utils.py:36] Started HHblits query
I0827 14:38:43.267431 140066848117952 utils.py:40] Finished HHblits query in 156.408 seconds
E0827 14:38:43.267613 140066848117952 hhblits.py:138] HHblits failed. HHblits stderr begin:
E0827 14:38:43.267664 140066848117952 hhblits.py:141] - 14:36:31.573 INFO: Searching 65983866 column state sequences.
E0827 14:38:43.267698 140066848117952 hhblits.py:141] - 14:36:32.498 INFO: Searching 15161831 column state sequences.
E0827 14:38:43.267728 140066848117952 hhblits.py:141] - 14:36:32.569 INFO: GARS_insertion.fas is in A2M, A3M or FASTA format
E0827 14:38:43.267756 140066848117952 hhblits.py:141] - 14:36:32.569 INFO: Iteration 1
E0827 14:38:43.267784 140066848117952 hhblits.py:141] - 14:36:32.607 INFO: Prefiltering database
E0827 14:38:43.267811 140066848117952 hhblits.py:141] - 14:37:27.399 INFO: HMMs passed 1st prefilter (gapless profile-profile alignment)  : 735240
E0827 14:38:43.267838 140066848117952 hhblits.py:141] - 14:38:40.391 INFO: HMMs passed 1st prefilter (gapless profile-profile alignment)  : 198439
E0827 14:38:43.267866 140066848117952 hhblits.py:141] - 14:38:41.184 INFO: HMMs passed 2nd prefilter (gapped profile-profile alignment)   : 2000
E0827 14:38:43.267893 140066848117952 hhblits.py:141] - 14:38:41.184 INFO: HMMs passed 2nd prefilter and not found in previous iterations : 2000
E0827 14:38:43.267920 140066848117952 hhblits.py:141] - 14:38:41.184 INFO: Scoring 2000 HMMs using HMM-HMM Viterbi alignment
E0827 14:38:43.267946 140066848117952 hhblits.py:141] - 14:38:41.286 INFO: Alternative alignment: 0
E0827 14:38:43.267974 140066848117952 hhblits.py:142] HHblits stderr end
Traceback (most recent call last):
  File "../run_alphafold.py", line 338, in <module>
    app.run(main)
  File "/home/linlab/.local/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/home/linlab/.local/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "../run_alphafold.py", line 310, in main
    predict_structure(
  File "../run_alphafold.py", line 170, in predict_structure
    feature_dict = data_pipeline.process(
  File "/home/linlab/Applications/alphafold/alphafold/data/pipeline.py", line 154, in process
    hhblits_bfd_uniclust_result = self.hhblits_bfd_uniclust_runner.query(
  File "/home/linlab/Applications/alphafold/alphafold/data/tools/hhblits.py", line 143, in query
    raise RuntimeError('HHblits failed\nstdout:\n%s\n\nstderr:\n%s\n' % (
RuntimeError: HHblits failed
stdout:

stderr:
- 14:36:31.573 INFO: Searching 65983866 column state sequences.

- 14:36:32.498 INFO: Searching 15161831 column state sequences.

- 14:36:32.569 INFO: GARS_insertion.fas is in A2M, A3M or FASTA format

- 14:36:32.569 INFO: Iteration 1

- 14:36:32.607 INFO: Prefiltering database

- 14:37:27.399 INFO: HMMs passed 1st prefilter (gapless profile-profile alignment)  : 735240

- 14:38:40.391 INFO: HMMs passed 1st prefilter (gapless profile-profile alignment)  : 198439

- 14:38:41.184 INFO: HMMs passed 2nd prefilter (gapped profile-profile alignment)   : 2000

- 14:38:41.184 INFO: HMMs passed 2nd prefilter and not found in previous iterations : 2000

- 14:38:41.184 INFO: Scoring 2000 HMMs using HMM-HMM Viterbi alignment

- 14:38:41.286 INFO: Alternative alignment: 0

**Comment by lugoly** [comment]
I have fixed the error.

Firstly, I run the script 
hhblits -i GARS_insertion.fas -cpu 4 -oa3m /tmp/tmptyl5pi44/output.a3m -o /dev/null -n 3 -e 0.001 -maxseq 1000000 -realign_max 100000 -maxfilt 100000 -min_prefilter_hits 1000 -d /data1/AF2_Database/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt -d /data1/AF2_Database/uniclust30/uniclust30_2018_08/uniclust30_2018_08

It turned out that the files in bfd cannot open. may be broken in tar process.

Then, I replaced the bfd folder by re-download the bfd database.

**Comment by xianyu-123** [comment]
i have the same error, but my error line in 94

  File "/home/wgj/wanggj/MyWorkSpace/tools/alphafold-2.3.1/alphafold/data/tools/hhsearch.py", line 94, in query
    raise RuntimeError(
RuntimeError: HHSearch failed:
stdout:


stderr:
- 12:03:19.238 INFO: /tmp/tmpotg_3ina/query.a3m is in A2M, A3M or FASTA format

- 12:03:19.238 WARNING: Ignoring invalid symbol '*' at pos. 668 in line 2 of /tmp/tmpotg_3ina/query.a3m

- 12:03:19.393 ERROR: [subseq from] Methionine-tRNA ligase n=3 Tax=Actinomycetes TaxID=1760 RepID=A0A516ELE7_9ACTN
- 12:03:19.393 ERROR: Error in /build/hhsuite-zKN5_w/hhsuite-3.2.0/src/hhalignment.cpp:1244: Compress:

- 12:03:19.393 ERROR:   sequences in /tmp/tmpotg_3ina/query.a3m do not all have the same number of columns, 

- 12:03:19.393 ERROR: 
e.g. first sequence and sequence UniRef90_A0A516ELE7/1-668.

- 12:03:19.393 ERROR: Check input format for '-M a2m' option and consider using '-M first' or '-M 50'
