### ISSUE TITLE
model

### ISSUE THREAD

**Issue by HGX-001** [kalininalab/alphafold_non_docker#16]
Hello,it can run with no problem,I have a problem,How i can run it with all 5 Model.

**Comment by sanjaysrikakulam** [comment]
Hi @HGX-001 

You can pass multiple model names in a comma-separated format to `-m` option

example: `-m "model_1,model_2,model_3,model_4,model_5`

**Comment by HGX-001** [comment]
Thank you @ sanjaysrikakulam, but I encountered a new problem, and its error is as follows：
(alphafold) [root@localhost alphafold]# bash run_alphafold.sh -d /mydata -o /iobio/public/softwares/alphafold/alphafoldoutput -m model_1 -f /iobio/public/softwares/alphafold/alphafold_non_docker/example/query.fasta -t 2020-05-14
/iobio/public/tools/anaconda3/envs/alphafold/lib/python3.8/site-packages/absl/flags/_validators.py:203: UserWarning: Flag --preset has a non-None default value; therefore, mark_flag_as_required will pass even if flag is not specified in the command line!
  warnings.warn(
I0907 19:03:13.094228 139764828165952 templates.py:836] Using precomputed obsolete pdbs /mydata/mmcif/obsolete.dat.
I0907 19:03:13.572609 139764828165952 xla_bridge.py:236] Unable to initialize backend 'tpu_driver': Not found: Unable to find driver in registry given worker: 
I0907 19:03:13.732445 139764828165952 xla_bridge.py:236] Unable to initialize backend 'tpu': Invalid argument: TpuPlatform is not available.
I0907 19:03:17.682091 139764828165952 run_alphafold.py:267] Have 1 models: ['model_1']
I0907 19:03:17.683088 139764828165952 run_alphafold.py:280] Using random seed 4290153824845353106 for the data pipeline
I0907 19:03:17.689317 139764828165952 jackhmmer.py:130] Launching subprocess "/iobio/public/tools/anaconda3/envs/alphafold/bin/jackhmmer -o /dev/null -A /tmp/tmp89rht1dd/output.sto --noali --F1 0.0005 --F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --cpu 8 -N 1 /iobio/public/softwares/alphafold/alphafold_non_docker/example/query.fasta /mydata/uniref90/uniref90.fasta"
I0907 19:03:17.933292 139764828165952 utils.py:36] Started Jackhmmer (uniref90.fasta) query
I0907 19:12:14.624025 139764828165952 utils.py:40] Finished Jackhmmer (uniref90.fasta) query in 536.690 seconds
I0907 19:12:14.625833 139764828165952 jackhmmer.py:130] Launching subprocess "/iobio/public/tools/anaconda3/envs/alphafold/bin/jackhmmer -o /dev/null -A /tmp/tmp058rnfpt/output.sto --noali --F1 0.0005 --F2 5e-05 --F3 5e-07 --incE 0.0001 -E 0.0001 --cpu 8 -N 1 /iobio/public/softwares/alphafold/alphafold_non_docker/example/query.fasta /mydata/mgnify/mgy_clusters_2018_12.fa"
I0907 19:12:14.934417 139764828165952 utils.py:36] Started Jackhmmer (mgy_clusters_2018_12.fa) query
I0907 19:23:37.884372 139764828165952 utils.py:40] Finished Jackhmmer (mgy_clusters_2018_12.fa) query in 682.950 seconds
I0907 19:23:37.909170 139764828165952 hhsearch.py:76] Launching subprocess "/iobio/public/tools/anaconda3/envs/alphafold/bin/hhsearch -i /tmp/tmp2ssap01j/query.a3m -o /tmp/tmp2ssap01j/output.hhr -maxseq 1000000 -d /mydata/pdb70/pdb70"
I0907 19:23:38.618400 139764828165952 utils.py:36] Started HHsearch query
I0907 19:25:09.295235 139764828165952 utils.py:40] Finished HHsearch query in 90.676 seconds
I0907 19:25:09.396180 139764828165952 hhblits.py:128] Launching subprocess "/iobio/public/tools/anaconda3/envs/alphafold/bin/hhblits -i /iobio/public/softwares/alphafold/alphafold_non_docker/example/query.fasta -cpu 4 -oa3m /tmp/tmpbzf6ucy6/output.a3m -o /dev/null -n 3 -e 0.001 -maxseq 1000000 -realign_max 100000 -maxfilt 100000 -min_prefilter_hits 1000 -d /mydata/bfd/bfd_metaclust_clu_complete_id30_c90_final_seq.sorted_opt -d /mydata/uniclust30/uniclust30_2018_08/uniclust30_2018_08"
I0907 19:25:09.681968 139764828165952 utils.py:36] Started HHblits query
I0907 22:24:32.124334 139764828165952 utils.py:40] Finished HHblits query in 10762.442 seconds
I0907 22:24:32.162243 139764828165952 templates.py:848] Searching for template for: None
W0907 22:24:32.163637 139764828165952 templates.py:131] Template structure not in release dates dict: 6mrr
I0907 22:24:32.163766 139764828165952 templates.py:698] None: hit 6mrr_A did not pass prefilter: Template is an exact subsequence of query with large coverage. Length ratio: 1.0.
I0907 22:24:32.163839 139764828165952 templates.py:893] Skipped invalid hit 6MRR_A foldit1; De novo protein, Foldit; 1.18A {synthetic construct}, error: None, warning: None
W0907 22:24:32.163901 139764828165952 templates.py:131] Template structure not in release dates dict: 6q64
I0907 22:24:32.164011 139764828165952 templates.py:715] Reading PDB entry from /mydata/mmcif/mmcif_files/6q64.cif. Query: GWSTELEKHREELKEFLKKEGITNVEIRIDNGRLEVRVEGGTERLKRFLEELRQKLEKKGYTVDIKIE, template: VKAYANAICDSIEKYNLDGFDIDYQPGYGHSGTLANYQTISPSGNNKMQVFIETLSARLRPAGRMLVM
I0907 22:24:32.514337 139764828165952 templates.py:270] Found an exact template match 6q64_A.
W0907 22:24:32.552261 139764828165952 templates.py:131] Template structure not in release dates dict: 4s3k
I0907 22:24:32.552517 139764828165952 templates.py:715] Reading PDB entry from /mydata/mmcif/mmcif_files/4s3k.cif. Query: GWSTELEKHREELKEFLKKEGITNVEIRIDNGRLEVRVEGGTERLKRFLEELRQKLEKKGYTVDIKIE, template: DTLLNNIVKTAKEQNFRDIHFDFEFLRPADKEAYIAFLQKAKKRLQDEQLLMSVA
I0907 22:24:33.460440 139764828165952 templates.py:270] Found an exact template match 4s3k_A.
W0907 22:24:33.512508 139764828165952 templates.py:131] Template structure not in release dates dict: 5jh8
I0907 22:24:33.513139 139764828165952 templates.py:715] Reading PDB entry from /mydata/mmcif/mmcif_files/5jh8.cif. Query: GWSTELEKHREELKEFLKKEGITNVEIRIDNGRLEVRVEGGTERLKRFLEELRQKLEKKGYTVDIKIE, template: SQAVANLVKFAQDKRFSGINVDFEAVAQGDRNNFSHFIQVLGRALHAKGLKLIVS
I0907 22:24:34.163246 139764828165952 templates.py:270] Found an exact template match 5jh8_A.
W0907 22:24:34.206485 139764828165952 templates.py:131] Template structure not in release dates dict: 1jnd
I0907 22:24:34.206843 139764828165952 templates.py:715] Reading PDB entry from /mydata/mmcif/mmcif_files/1jnd.cif. Query: GWSTELEKHREELKEFLKKEGITNVEIRIDNGRLEVRVEGGTERLKRFLEELRQKLEKKGYTVDIKIE, template: GFIRSAYELVKTYGFDGLDLAYQFPKNKPRKVHGDLGLAWKSIKKLFTGDFIVDPHAALHKEQFTALVRDVKDSLRADGFLLSLT
I0907 22:24:34.540835 139764828165952 templates.py:270] Found an exact template match 1jnd_A.
W0907 22:24:34.564356 139764828165952 templates.py:131] Template structure not in release dates dict: 5y2a
I0907 22:24:34.564620 139764828165952 templates.py:715] Reading PDB entry from /mydata/mmcif/mmcif_files/5y2a.cif. Query: GWSTELEKHREELKEFLKKEGITNVEIRIDNGRLEVRVEGGTERLKRFLEELRQKLEKKGYTVDIKIE, template: RKFVVHAVDFLEQYGFDGLDLDWEYPKCWQVECEKGPDSDKQGFADLVKELRKAFNRRGMLLSAA
I0907 22:24:35.255799 139764828165952 templates.py:270] Found an exact template match 5y2a_B.
W0907 22:24:35.286214 139764828165952 templates.py:131] Template structure not in release dates dict: 4wiw
I0907 22:24:35.286480 139764828165952 templates.py:715] Reading PDB entry from /mydata/mmcif/mmcif_files/4wiw.cif. Query: GWSTELEKHREELKEFLKKEGITNVEIRIDNGRLEVRVEGGTERLKRFLEELRQKLEKKGYTVDIKIE, template: EKLIGEIVVLLKNTNADGVVIDFETPLDYGDVKDPYDGVRNDLTAFMESLHSELQSMNKLVVM
I0907 22:24:37.764686 139764828165952 templates.py:270] Found an exact template match 4wiw_B.
W0907 22:24:37.843966 139764828165952 templates.py:131] Template structure not in release dates dict: 4wiw
I0907 22:24:37.844714 139764828165952 templates.py:715] Reading PDB entry from /mydata/mmcif/mmcif_files/4wiw.cif. Query: GWSTELEKHREELKEFLKKEGITNVEIRIDNGRLEVRVEGGTERLKRFLEELRQKLEKKGYTVDIKIE, template: EKLIGEIVVLLKNTNADGVVIDFETPLDYGDVKDPYDGVRNDLTAFMESLHSELQSMNKLVVM
I0907 22:24:40.075711 139764828165952 templates.py:270] Found an exact template match 4wiw_D.
W0907 22:24:40.114134 139764828165952 templates.py:131] Template structure not in release dates dict: 6jm7
I0907 22:24:40.114414 139764828165952 templates.py:715] Reading PDB entry from /mydata/mmcif/mmcif_files/6jm7.cif. Query: GWSTELEKHREELKEFLKKEGITNVEIRIDNGRLEVRVEGGTERLKRFLEELRQKLEKKGYTVDIKIE, template: QNFIQTSLAMILEYNFDGLDVDWEYPNRRDTVHGEDDIEQFSTLLKELREEFDNYGLLLTV
I0907 22:24:40.441472 139764828165952 templates.py:270] Found an exact template match 6jm7_A.
W0907 22:24:40.466569 139764828165952 templates.py:131] Template structure not in release dates dict: 6jmb
I0907 22:24:40.466855 139764828165952 templates.py:715] Reading PDB entry from /mydata/mmcif/mmcif_files/6jmb.cif. Query: GWSTELEKHREELKEFLKKEGITNVEIRIDNGRLEVRVEGGTERLKRFLEELRQKLEKKGYTVDIKIE, template: QNFIQTSLAMILEYNFDGLDVDWEYPNRRDTVHGEDDIEQFSTLLKELREEFDNYGLLLTV
I0907 22:24:40.720153 139764828165952 templates.py:270] Found an exact template match 6jmb_A.
W0907 22:24:40.750575 139764828165952 templates.py:131] Template structure not in release dates dict: 4q6t
I0907 22:24:40.751420 139764828165952 templates.py:715] Reading PDB entry from /mydata/mmcif/mmcif_files/4q6t.cif. Query: GWSTELEKHREELKEFLKKEGITNVEIRIDNGRLEVRVEGGTERLKRFLEELRQKLEKKGYTVDIKIE, template: GTVKQLVKLAKEGGFAGINLDFEKVEPRNRAAFCAFVKTLGNALHASNKKLIIS
I0907 22:24:41.418202 139764828165952 templates.py:270] Found an exact template match 4q6t_A.
W0907 22:24:41.442383 139764828165952 templates.py:131] Template structure not in release dates dict: 3oa5
I0907 22:24:41.442660 139764828165952 templates.py:715] Reading PDB entry from /mydata/mmcif/mmcif_files/3oa5.cif. Query: GWSTELEKHREELKEFLKKEGITNVEIRIDNGRLEVRVEGGTERLKRFLEELRQKLEKKGYTVDIKIE, template: TNFVEGIKDFFQRFPMFSHLDIDWEYPGSIGAGNPNSPDDGANFAILIQQITDAKISNLKGISI
I0907 22:24:42.259624 139764828165952 templates.py:270] Found an exact template match 3oa5_B.
W0907 22:24:42.295166 139764828165952 templates.py:131] Template structure not in release dates dict: 5y2c
I0907 22:24:42.295439 139764828165952 templates.py:715] Reading PDB entry from /mydata/mmcif/mmcif_files/5y2c.cif. Query: GWSTELEKHREELKEFLKKEGITNVEIRIDNGRLEVRVEGGTERLKRFLEELRQKLEKKGYTVDIKIE, template: RKFVVHAVDFLEQYGFDGLDLDWLYPKCWQVECEKGPDSDKQGFADLVKELRKAFNRRGMLLSA
I0907 22:24:42.970783 139764828165952 templates.py:270] Found an exact template match 5y2c_A.
W0907 22:24:42.999474 139764828165952 templates.py:131] Template structure not in release dates dict: 5cuk
I0907 22:24:42.999753 139764828165952 templates.py:715] Reading PDB entry from /mydata/mmcif/mmcif_files/5cuk.cif. Query: GWSTELEKHREELKEFLKKEGITNVEIRIDNGRLEVRVEGGTERLKRFLEELRQKLEKKGYTVDIKIE, template: RLQVRLPQLGAVEVQVLHGHGQLQIEISASPGSLALLQQARGELLERLQRLHPEQPVQLTF
I0907 22:24:43.080716 139764828165952 templates.py:270] Found an exact template match 5cuk_A.
W0907 22:24:43.086320 139764828165952 templates.py:131] Template structure not in release dates dict: 4a5q
I0907 22:24:43.086554 139764828165952 templates.py:715] Reading PDB entry from /mydata/mmcif/mmcif_files/4a5q.cif. Query: GWSTELEKHREELKEFLKKEGITNVEIRIDNGRLEVRVEGGTERLKRFLEELRQKLEKKGYTVDIKIE, template: NFVEGIKDFFQRFPMFSHLDIDWEYPGSIGAGNPNSPDDGANFAILIQQITDAKISNLKGISI
I0907 22:24:44.674898 139764828165952 templates.py:270] Found an exact template match 4a5q_E.
W0907 22:24:44.713435 139764828165952 templates.py:131] Template structure not in release dates dict: 5y2b
I0907 22:24:44.713730 139764828165952 templates.py:715] Reading PDB entry from /mydata/mmcif/mmcif_files/5y2b.cif. Query: GWSTELEKHREELKEFLKKEGITNVEIRIDNGRLEVRVEGGTERLKRFLEELRQKLEKKGYTVDIKIE, template: KFVQHAVAFLEKYGFDGLDLDWEYPKCWQVDCSKGPDSDKQGFADLVHELSAVLKPKGLLLSA
I0907 22:24:45.020054 139764828165952 templates.py:270] Found an exact template match 5y2b_A.
W0907 22:24:45.057088 139764828165952 templates.py:131] Template structure not in release dates dict: 4lgx
I0907 22:24:45.057378 139764828165952 templates.py:715] Reading PDB entry from /mydata/mmcif/mmcif_files/4lgx.cif. Query: GWSTELEKHREELKEFLKKEGITNVEIRIDNGRLEVRVEGGTERLKRFLEELRQKLEKKGYTVDIKIE, template: AVFIRSVQQVIKQYHLDGIDLDWEYPVNGAWGLVESQPADRANFTLLLAELHKALDKGKLLTI
I0907 22:24:45.375033 139764828165952 templates.py:270] Found an exact template match 4lgx_A.
W0907 22:24:45.423814 139764828165952 templates.py:131] Template structure not in release dates dict: 4w5u
I0907 22:24:45.424885 139764828165952 templates.py:715] Reading PDB entry from /mydata/mmcif/mmcif_files/4w5u.cif. Query: GWSTELEKHREELKEFLKKEGITNVEIRIDNGRLEVRVEGGTERLKRFLEELRQKLEKKGYTVDIKIE, template: GFAQSCYNLVHDPRWDGVFDGIDIDWEYPNACGLTCDSSGPDAFRNLMAALRSTFGDELVTAA
I0907 22:24:46.509156 139764828165952 templates.py:270] Found an exact template match 4w5u_A.
W0907 22:24:46.537168 139764828165952 templates.py:131] Template structure not in release dates dict: 6jav
I0907 22:24:46.537454 139764828165952 templates.py:715] Reading PDB entry from /mydata/mmcif/mmcif_files/6jav.cif. Query: GWSTELEKHREELKEFLKKEGITNVEIRIDNGRLEVRVEGGTERLKRFLEELRQKLEKKGYTVDIKIE, template: FVQHAVAFLEKYGFDGLDLDWEYPKCWQVDCSKGPDSDKQGFADLVHELSAVLKPKGLLLSA
I0907 22:24:46.795663 139764828165952 templates.py:270] Found an exact template match 6jav_A.
W0907 22:24:46.818569 139764828165952 templates.py:131] Template structure not in release dates dict: 3cz8
I0907 22:24:46.818833 139764828165952 templates.py:715] Reading PDB entry from /mydata/mmcif/mmcif_files/3cz8.cif. Query: GWSTELEKHREELKEFLKKEGITNVEIRIDNGRLEVRVEGGTERLKRFLEELRQKLEKKGYTVDIKIE, template: NLVNNIYDLVSTRGYGGVTIDFEQVSAADRDLFTGFLRQLRDRLQAGGYVLTI
I0907 22:24:47.246659 139764828165952 templates.py:270] Found an exact template match 3cz8_A.
W0907 22:24:47.277142 139764828165952 templates.py:131] Template structure not in release dates dict: 3cz8
I0907 22:24:47.277404 139764828165952 templates.py:715] Reading PDB entry from /mydata/mmcif/mmcif_files/3cz8.cif. Query: GWSTELEKHREELKEFLKKEGITNVEIRIDNGRLEVRVEGGTERLKRFLEELRQKLEKKGYTVDIKIE, template: NLVNNIYDLVSTRGYGGVTIDFEQVSAADRDLFTGFLRQLRDRLQAGGYVLTI
I0907 22:24:47.657337 139764828165952 templates.py:270] Found an exact template match 3cz8_B.
I0907 22:24:47.690633 139764828165952 pipeline.py:200] Uniref90 MSA size: 2 sequences.
I0907 22:24:47.690847 139764828165952 pipeline.py:201] BFD MSA size: 1 sequences.
I0907 22:24:47.690941 139764828165952 pipeline.py:202] MGnify MSA size: 2 sequences.
I0907 22:24:47.691000 139764828165952 pipeline.py:203] Final (deduplicated) MSA size: 2 sequences.
I0907 22:24:47.691226 139764828165952 pipeline.py:205] Total number of templates (NB: this can include bad templates and is later filtered to top 4): 20.
I0907 22:24:47.716325 139764828165952 run_alphafold.py:142] Running model model_1
2021-09-07 22:24:52.737474: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/intel/composer_xe_2013.2.146/compiler/lib/intel64:/opt/intel/mic/coi/host-linux-release/lib:/opt/intel/mic/myo/lib:/opt/intel/composer_xe_2013.2.146/mpirt/lib/intel64:/opt/intel/composer_xe_2013.2.146/ipp/../compiler/lib/intel64:/opt/intel/composer_xe_2013.2.146/ipp/lib/intel64:/opt/intel/composer_xe_2013.2.146/compiler/lib/intel64:/opt/intel/composer_xe_2013.2.146/mkl/lib/intel64:/opt/intel/composer_xe_2013.2.146/tbb/lib/intel64:/opt/intel/composer_xe_2013.2.146/compiler/lib/intel64:/opt/intel/mic/coi/host-linux-release/lib:/opt/intel/mic/myo/lib:/opt/intel/composer_xe_2013.2.146/mpirt/lib/intel64:/opt/intel/composer_xe_2013.2.146/ipp/../compiler/lib/intel64:/opt/intel/composer_xe_2013.2.146/ipp/lib/intel64:/opt/intel/composer_xe_2013.2.146/compiler/lib/intel64:/opt/intel/composer_xe_2013.2.146/mkl/lib/intel64:/opt/intel/composer_xe_2013.2.146/tbb/lib/intel64:/usr/lib64/mpich-3.2/lib
2021-09-07 22:24:52.799872: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1766] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
I0907 22:24:54.470149 139764828165952 model.py:131] Running predict with shape(feat) = {'aatype': (4, 68), 'residue_index': (4, 68), 'seq_length': (4,), 'template_aatype': (4, 4, 68), 'template_all_atom_masks': (4, 4, 68, 37), 'template_all_atom_positions': (4, 4, 68, 37, 3), 'template_sum_probs': (4, 4, 1), 'is_distillation': (4,), 'seq_mask': (4, 68), 'msa_mask': (4, 508, 68), 'msa_row_mask': (4, 508), 'random_crop_to_size_seed': (4, 2), 'template_mask': (4, 4), 'template_pseudo_beta': (4, 4, 68, 3), 'template_pseudo_beta_mask': (4, 4, 68), 'atom14_atom_exists': (4, 68, 14), 'residx_atom14_to_atom37': (4, 68, 14), 'residx_atom37_to_atom14': (4, 68, 37), 'atom37_atom_exists': (4, 68, 37), 'extra_msa': (4, 5120, 68), 'extra_msa_mask': (4, 5120, 68), 'extra_msa_row_mask': (4, 5120), 'bert_mask': (4, 508, 68), 'true_msa': (4, 508, 68), 'extra_has_deletion': (4, 5120, 68), 'extra_deletion_value': (4, 5120, 68), 'msa_feat': (4, 508, 68, 49), 'target_feat': (4, 68, 22)}
2021-09-07 22:24:56.108880: W external/org_tensorflow/tensorflow/stream_executor/gpu/asm_compiler.cc:81] Couldn't get ptxas version string: Internal: Running ptxas --version returned 32512
2021-09-07 22:24:56.401360: F external/org_tensorflow/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc:479] ptxas returned an error during compilation of ptx to sass: 'Internal: ptxas exited with non-zero error code 32512, output: '  If the error message indicates that a file could not be written, please verify that sufficient filesystem space is provided.
Fatal Python error: Aborted

Thread 0x00007f1d88ef5740 (most recent call first):
  File "/iobio/public/tools/anaconda3/envs/alphafold/lib/python3.8/site-packages/jax/interpreters/xla.py", line 386 in backend_compile
  File "/iobio/public/tools/anaconda3/envs/alphafold/lib/python3.8/site-packages/jax/interpreters/xla.py", line 323 in xla_primitive_callable
  File "/iobio/public/tools/anaconda3/envs/alphafold/lib/python3.8/site-packages/jax/_src/util.py", line 188 in cached
  File "/iobio/public/tools/anaconda3/envs/alphafold/lib/python3.8/site-packages/jax/_src/util.py", line 195 in wrapper
  File "/iobio/public/tools/anaconda3/envs/alphafold/lib/python3.8/site-packages/jax/interpreters/xla.py", line 274 in apply_primitive
  File "/iobio/public/tools/anaconda3/envs/alphafold/lib/python3.8/site-packages/jax/core.py", line 612 in process_primitive
  File "/iobio/public/tools/anaconda3/envs/alphafold/lib/python3.8/site-packages/jax/core.py", line 267 in bind
  File "/iobio/public/tools/anaconda3/envs/alphafold/lib/python3.8/site-packages/jax/_src/lax/lax.py", line 386 in shift_right_logical
  File "/iobio/public/tools/anaconda3/envs/alphafold/lib/python3.8/site-packages/jax/_src/prng.py", line 228 in threefry_seed
  File "/iobio/public/tools/anaconda3/envs/alphafold/lib/python3.8/site-packages/jax/_src/prng.py", line 190 in seed_with_impl
  File "/iobio/public/tools/anaconda3/envs/alphafold/lib/python3.8/site-packages/jax/_src/random.py", line 105 in PRNGKey
  File "/iobio/public/softwares/alphafold/alphafold/model/model.py", line 133 in predict
  File "/iobio/public/softwares/alphafold/run_alphafold.py", line 149 in predict_structure
  File "/iobio/public/softwares/alphafold/run_alphafold.py", line 284 in main
  File "/iobio/public/tools/anaconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 258 in _run_main
  File "/iobio/public/tools/anaconda3/envs/alphafold/lib/python3.8/site-packages/absl/app.py", line 312 in run
  File "/iobio/public/softwares/alphafold/run_alphafold.py", line 310 in <module>

I installed these libraries exactly according to your steps.

**Comment by sanjaysrikakulam** [comment]
Hi @HGX-001 

It looks like you have some issues with your CUDA setup and some libraries are not available or something. Your CUDA binaries and libraries should be available in $PATH and $LD_LIBRARY_PATH. Please fix your CUDA installation or make it available in the path of the user then this issue should be fixed.

**Comment by HGX-001** [comment]
Hi@ sanjaysrikakulam,Thank you very much,I have solve the proble,after set the CUDA  $PATH and $LD_LIBRARY_PATH.

**Comment by HGX-001** [comment]
Hello, thank you very much. You can help me solve the previous problem. Now I have a new problem and want to consult you. If you can help me, I'll be very grateful to you.I find that i can not use print() to print the jax.numpy.ndarrray and any other tensor in the alphafold code.I don't know how you understand the contents of these tensors, I hope you can give me some suggestions to print out these tensors.发自我的iPhone------------------ Original ------------------From: Sanjay Kumar Srikakulam  ***@***.***>Date: Thu,Sep 9,2021 2:00 PMTo: kalininalab/alphafold_non_docker ***@***.***>Cc: HGX-001 ***@***.***>, Mention ***@***.***>Subject: Re: [kalininalab/alphafold_non_docker] model (#16)
Closed #16.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/kalininalab/alphafold_non_docker/issues/16#event-5276213582",
"url": "https://github.com/kalininalab/alphafold_non_docker/issues/16#event-5276213582",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by sanjaysrikakulam** [comment]
Hi @HGX-001 

I am afraid that I cannot answer this question, you will have to create a ticket in AF2's github repository regarding this and maybe someone who knows about this better can help you.
