### ISSUE TITLE
Unable to find CIF files 

### ISSUE THREAD

**Issue by Geraldene** [kalininalab/alphafold_non_docker#18]
I am getting the following error: 
`ValueError: Could not find CIFs in /path/to/mmcif_files`

I have checked and the files are present, is there a way around this?

**Comment by sanjaysrikakulam** [comment]
Hi @Geraldene 

Please make sure you have the proper directory structure as described here https://github.com/deepmind/alphafold#genetic-databases and also check if your user has required read permissions to the download/data directory.

**Comment by Geraldene** [comment]
@sanjaysrikakulam The directory has the proper structure and the 'download/data directory' has read permissions but I am still encountering the same error

**Comment by sanjaysrikakulam** [comment]
Hi @Geraldene,

In that case please edit the path in the variable `template_mmcif_dir` in `run_alphafold.sh` script. The script is designed to follow the AF2's data directory structure, the simplest solution, for now, would be to manually change the path within the script. To further troubleshoot please share the tree structure of your 'data directory which contains all the downloaded databases for AF2.
