### ISSUE TITLE
how to run pTM flavour of AlphaFold2? (i.e to get PAE and TM)

### ISSUE THREAD

**Issue by DLMURPHY150** [kalininalab/alphafold_non_docker#21]
Hi guys,

This is not per se' an issue but I've just used your framework to run non-docker AlphaFold2 with "full_dbs" preset for which I was expected in the output per-model .pkl files the PAE matrix and predicted TM-score which I did not get. My understanding was that running "full_dbs" preset runs the ptm network instead of casp14?!

Can anyone check this or confirm how to run the ptm version in AlphaFold2 with your main python script please?!

Thanks,
David

**Comment by sanjaysrikakulam** [comment]
Hi @DLMURPHY150 

Apologies for the delayed response. I have updated the non-docker version to support everything that AF2 docker does. Using the latest version now should enable pTM flavour as well (use *-m monomer_ptm -c full_dbs*).
