### ISSUE TITLE
Incorrect variable name

### ISSUE THREAD

**Issue by zappuf** [kalininalab/alphafold_non_docker#24]
Please change `Download MGnify database` in `download_db.sh` to the following
```
# Download MGnify database
echo "Downloading MGnify database"
mgnify_filename="mgy_clusters_2018_12.fa.gz"
wget -P "$mgnify" "https://storage.googleapis.com/alphafold-databases/casp14_versions/${mgnify_filename}"
(cd "$mgnify" && gunzip "$mgnify/$mgnify_filename")
```

**Comment by sanjaysrikakulam** [comment]
Hi @zappuf 

Thank you for pointing the issue, I made several changes in the last update and somehow missed it. Now I have updated and migrated everything to variable substitution.
