### ISSUE TITLE
missing CIFS in pdb_mmcif?

### ISSUE THREAD

**Issue by ryao-mdanderson** [kalininalab/alphafold_non_docker#25]
Hello, Kalininalab support member!

I am trying alphafold 2.1.1 and this non docker version of set up. Thank you very much for providing this non-docker version, it helps us to set up on HPC cluster.

The testing I experienced is can't find CIFs, 

(alphafold-2.1.1) [user@cdragon096 alphafold]$ bash run_alphafold.sh -d $HOME/alphafold/alphafold_data -o ./dummy_test/ -m model_1 -f $HOME/alphafold/alphafold_non_docker/example/query.fasta -t 2020-05-14 -g False
Unknown model preset! Using default ('monomer')
E1118 12:13:41.684854 46912496434880 templates.py:837] Could not find CIFs in $HOME/alphafold/alphafold_data/pdb_mmcif/mmcif_files
Traceback (most recent call last):
  File "/home/ryao/alphafold/run_alphafold.py", line 427, in <module>
    app.run(main)
  File "/risapps/rhel7/python/3.7.3/envs/alphafold-2.1.1/lib/python3.8/site-packages/absl/app.py", line 312, in run
    _run_main(main, args)
  File "/risapps/rhel7/python/3.7.3/envs/alphafold-2.1.1/lib/python3.8/site-packages/absl/app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "/home/ryao/alphafold/run_alphafold.py", line 341, in main
    template_featurizer = templates.HhsearchHitFeaturizer(
  File "$HOME/alphafold/alphafold/data/templates.py", line 838, in __init__
    raise ValueError(f'Could not find CIFs in {self._mmcif_dir}')
ValueError: Could not find CIFs in $HOME/alphafold_data/pdb_mmcif/mmcif_files
(alphafold-2.1.1) 

Would you please advise if I have missing anything?

Regards,
Rong

**Comment by ryao-mdanderson** [comment]
Please ignore my message. I figured out 2 places to be fixed

1, I  should use "-t 2021-11-01" to do the testing;
2, refer to https://github.com/deepmind/alphafold/issues/54
there is a bug fix, in data directory mgnify, set up symbolic link
 ln -s mgy_clusters.fa mgy_clusters_2018_12.fa

**Comment by sanjaysrikakulam** [comment]
Hi @ryao-mdanderson 

Thank you for the solutions. Yes, mgnify database name should be corrected if you are using latest version of AF2. I also updated our download_db.sh accordingly in the latest update.
