### ISSUE TITLE
Wrong variable names in download_database.sh

### ISSUE THREAD

**Issue by Moa53** [kalininalab/alphafold_non_docker#27]
Hello,

On line 77, you forgot the $ for uniprot and pdb_seqres mkdir

`mkdir "$params" "$mgnify" "$pdb70" "$pdb_mmcif" "$mmcif_download_dir" "$mmcif_files" "$uniclust30" "$uniref90" "uniprot" "pdb_seqres"`

should be 

`mkdir "$params" "$mgnify" "$pdb70" "$pdb_mmcif" "$mmcif_download_dir" "$mmcif_files" "$uniclust30" "$uniref90" "$uniprot" "$pdb_seqres"`

Greetings,
David

**Comment by sanjaysrikakulam** [comment]
Hi @Moa53 

Thank you! Its fixed now!
