### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by kdpan** [kalininalab/alphafold_non_docker#28]
sudo ./run_alphafold.sh -d /home/panfulu/alphafold_database -o ./ -f P00519-2.fasta -t 2020-05-14

/var/tmp/sclLAKGtd: line 8: ./run_alphafold.sh: Permission denied

**Comment by sanjaysrikakulam** [comment]
Ho @kdpan 

Please check if you have proper permissions on the script?

`chmod 755 run_alphafold.sh`

**Comment by sanjaysrikakulam** [comment]
Also, you do not need sudo to run alphafold. You might have cloned the repo using a different user and then running the script as a sudo user and the permission denied might be due to that.

**Comment by kdpan** [comment]
Thank you very much !!!
