### ISSUE TITLE
Jax 

### ISSUE THREAD

**Issue by kdpan** [kalininalab/alphafold_non_docker#29]
Is any Jax version compatible with CUDA 10.2?

**Comment by sanjaysrikakulam** [comment]
Hi @kdpan 

Please check here https://github.com/google/jax/discussions/6236

**Comment by kdpan** [comment]
Hi@**sanjaysrikakulam**
Thank you!!!
However,  that didn't work，the version of jax requires version 0.1.74, and the cuda10. 2. only Jax 0.1.71 can be installed at most.

**Comment by sanjaysrikakulam** [comment]
Hi @kdpan 

In that case, is it possible to downgrade your JAX version? or upgrade the CUDA version?

**Comment by hegelab** [comment]
This may be good to change in the README.md:

pip install --upgrade jax jaxlib==0.1.69+cuda111 -f https://storage.googleapis.com/jax-releases/jax_releases.html

pip install jax==0.2.20 jaxlib==0.1.69+cuda111 -f https://storage.googleapis.com/jax-releases/jax_releases.html
