### ISSUE TITLE
FATAL Flags parsing error

### ISSUE THREAD

**Issue by mingyue80** [kalininalab/alphafold_non_docker#34]
I'm consistently running into this issue when trying to run the non-docker AP2 install. Followed directions and everything installed just fine. Downloaded run_alphafold.sh and tried to run the script, I consistently got the following error:

FATAL Flags parsing error: flag --use_gpu_relax=None: Flag --use_gpu_relax must have a value other than None.
Pass --helpshort or --helpfull to see help on flags.

I don't know where this setting is coming from, since it's not part of the script. I'm running Ubuntu 20.04.3 LTS, cuda version 11.5 v11.5.119, and nvidia-smi returns the following:
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.29.05    Driver Version: 495.29.05    CUDA Version: 11.5     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A4000    On   | 00000000:19:00.0 Off |                  Off |
| 41%   34C    P8     8W / 140W |     13MiB / 16117MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA RTX A4000    On   | 00000000:1A:00.0 Off |                  Off |
| 41%   36C    P8     7W / 140W |     13MiB / 16117MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA RTX A4000    On   | 00000000:67:00.0 Off |                  Off |
| 41%   34C    P8     6W / 140W |     13MiB / 16117MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  NVIDIA RTX A4000    On   | 00000000:68:00.0  On |                  Off |
| 41%   37C    P8     9W / 140W |    352MiB / 16116MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

**Comment by sanjaysrikakulam** [comment]
Hi,

It looks like AF2 has made a new release a few days ago which adds new GPU relaxation stuff. The bash script in this repo is not yet updated (I will do this as soon as possible) to adapt to the changes. So, please use AF2's v2.1.1 release (https://github.com/deepmind/alphafold/releases) instead of the latest v2.1.2. This should fix your problems.

**Comment by mingyue80** [comment]
rolling back to AF2 v2.1.1 solved the issues for me, thank you.

**Comment by TaoDFang** [comment]
I also run into this problem . Did anyone figure out how to solve this problem besides rolling back to v2.1.1 ?

**Comment by TaoDFang** [comment]
Ah Even if i used v2.1.1, it still has problem ...

**Comment by g-sutherland** [comment]
Did anyone manage to update the bash script for the GPU relaxation? Thanks in advance!

**Comment by sanjaysrikakulam** [comment]
Hi All,

Sorry for the delay (too hectic lately), I have updated the bash script along with the documentation in Readme. The bash script now works with AF2 version 2.2.0. If you encounter any problem please create a new ticket.
