### ISSUE TITLE
fasta_path syntax error

### ISSUE THREAD

**Issue by ianandersonlol** [kalininalab/alphafold_non_docker#4]
I am recieving the following error when trying to run the example. Do you have nay idea? `./example/query.fasta` is definitely a string. 
```
alphafold$ bash run_alphafold.sh -d ./alphafold_data/ -o ./dummy_test/ -m model_1 -f ./example/query.fasta -t 2021-07-27
  File "/home/user/alphafold/run_alphafold.py", line 96
    fasta_path: str,
              ^
SyntaxError: invalid syntax
```

**Comment by sanjaysrikakulam** [comment]
Hi @ianandersonlol 

Sorry, I am unable to reproduce your error. I cloned the repo and ran the script, maybe use the absolute path instead of the relative path.

**Comment by ianandersonlol** [comment]
Thanks, I'll give it a try!
