### ISSUE TITLE
run only 1 of the 5 models for AF v2.2.0 monomer via bash command-line?

### ISSUE THREAD

**Issue by avilella** [kalininalab/alphafold_non_docker#44]
Hi,

We are running the bash run_alphafold.sh script in our non-docker installation via this repo (thanks for the efforts, if you leave us a name, address and t-shirt size, we will send you a t-shirt!).

Question: in the older version of the bash script, I was able to specify "model_1" for AF to run only 1 of the 5 models. Can I do the same in v2.2.0? What name is model_4? Thanks in advance.

**Comment by sanjaysrikakulam** [comment]
Hi @avilella 

Thank you! Please leave me your email id and I will send you the details.

The model names feature was dropped in [version 2.1.1](https://github.com/kalininalab/alphafold_non_docker#api-changes-between-v200-and-v211). To change the number of models AF2 suggests editing the `MODEL_PRESETS` dictionary located under `alphafold/model/config.py`. Please refer to these threads for more information.

1. https://github.com/deepmind/alphafold/issues/405
2. https://github.com/deepmind/alphafold/issues/230

Hope this helps!

**Comment by avilella** [comment]
Excellent, thank you.

Email me to my username followed by gmail.com.

**Comment by sanjaysrikakulam** [comment]
Thank you! :-)
