### ISSUE TITLE
Change of jaxlib-cuda wheel source

### ISSUE THREAD

**Issue by quailwwk** [kalininalab/alphafold_non_docker#46]
Hi, it seems like the index file of jaxlib-cuda has been changed to https://storage.googleapis.com/jax-releases/jax_cuda_releases.html)](https://storage.googleapis.com/jax-releases/jax_cuda_releases.html according to https://github.com/google/jax/issues/11087#issuecomment-1157964575

**Comment by xingbanbin** [comment]
Thanks, I watched your sharing to solve this problem. Here's the address I used:

https://storage.googleapis.com/jax-releases/jax_cuda_releases.html

**Comment by sanjaysrikakulam** [comment]
The installation manual is updated now. Sorry for the delay.
