### ISSUE TITLE
-m option

### ISSUE THREAD

**Issue by arikat** [kalininalab/alphafold_non_docker#5]
Hi! Thank you for this non docker implementation!

I'm trying to generate multiple models with alphafold; it is my understanding that this requires use of the -m option.

I can get the script to work if I input model_1 in the -m option, but if I try a comma separated list with more than model_1 (or even just input any other name other than model_1), I get the following error:

> Traceback (most recent call last):
>   File "/apps/gb/AlphaFold/2.0.0/alphafold/run_alphafold.py", line 303, in <module>
>     app.run(main)
>   File "/apps/gb/AlphaFold/2.0.0/lib/python3.7/site-packages/absl/app.py", line 312, in run
>     _run_main(main, args)
>   File "/apps/gb/AlphaFold/2.0.0/lib/python3.7/site-packages/absl/app.py", line 258, in _run_main
>     sys.exit(main(argv))
>   File "/apps/gb/AlphaFold/2.0.0/alphafold/run_alphafold.py", line 253, in main
>     model_config = config.model_config(model_name)
>   File "/apps/gb/AlphaFold/2.0.0/alphafold/alphafold/model/config.py", line 32, in model_config
>     raise ValueError(f'Invalid model name {name}.')
> ValueError: Invalid model name model_2.

Here's the command I'm running:
**bash $ROOTALPHAFOLD/alphafold/run_alphafold.sh -d /db/AlphaFold -o ./test5/ -m model_1, model_2 -f ./fasta.fa -t 2020-05-14 -b True**

**Comment by sanjaysrikakulam** [comment]
Hi @arikat 

Probably AF2 does not allow names other than "model_<number>". The problem is it should just be separated by a comma and no extra space. In your command, there is a space between the comma and 2nd models name. I tried running it without space and with the AF2 suggested model naming scheme "model_1,model_2" and it works for me. Please try without space and it should work.

**Comment by arikat** [comment]
> Hi @arikat
> 
> Probably AF2 does not allow names other than "model_". The problem is it should just be separated by a comma and no extra space. In your command, there is a space between the comma and 2nd models name. I tried running it without space and with the AF2 suggested model naming scheme "model_1,model_2" and it works for me. Please try without space and it should work.

Thank you, that worked!
