### ISSUE TITLE
Update to Alphafold 2.3.0?

### ISSUE THREAD

**Issue by avilella** [kalininalab/alphafold_non_docker#54]
Hi,

There was a recent release of Alphafold, v.2.3.0, which amongst other things, improves the GPU VMEM efficiency of some parts of the computation.

https://github.com/deepmind/alphafold/releases/tag/v2.3.0

There don't seem to be any (?) changes in the parameters for the CLI, thus would a simple 'git pull' suffice for having the alphafold_non_docker installation updated?

The only parameter update I can see is:

- number of recycling iterations can now be controlled, and added an option to run single chains on the multimer model.

Thx in advance,

**Comment by sanjaysrikakulam** [comment]
Hi @avilella 

I am just back from vacation. I will update the repo with the latest changes soon.

**Comment by cb4github** [comment]
Dear Development Team,

Thanks for your continued attention to this matter, but can you please update the content in the readme page accordingly?

At this typing arguably this issue has been closed prematurely before the documentation contained in the readme page has been updated accordingly concerning the versions of alphafold, cudatoolkit, and perhaps others.

Again, at my typing I still see on the landing/#readme page the following.

1. The reference in the section [Download alphafold release v2.2.0](https://github.com/kalininalab/alphafold_non_docker#download-alphafold-release-v220) to alphafold v2.2.0 vice v2.3.0.
2. The reference in the section [Install dependencies](https://github.com/kalininalab/alphafold_non_docker#install-dependencies) to `conda install... cudatoolkit==11.0.3...` vice `ARG CUDA=11.1.1` mentioned in the [current Dockerfile](https://github.com/deepmind/alphafold/blob/9b18d6a966b9b08b2095dd77d8414a68d3d31fc9/docker/Dockerfile).

Please advise. Thanks.
Best, CB

**Comment by Old-Shatterhand** [comment]
Dear @cb4github,

thank you for participating in this discussion. I closed the issue because there is a [pending PR](https://github.com/kalininalab/alphafold_non_docker/pull/56) solving precisely that issue and we're currently evaluating the PR. As soon as this is done, the documentation will be updated.

Anyways, I'm not sure, what you mean by 

> 2. The reference in the section [Install dependencies](https://github.com/kalininalab/alphafold_non_docker#install-dependencies) to conda install... cudatoolkit==11.0.3... vice ARG CUDA=11.1.1 mentioned in the [current Dockerfile](https://github.com/deepmind/alphafold/blob/9b18d6a966b9b08b2095dd77d8414a68d3d31fc9/docker/Dockerfile).

The version of cudatoolkit, CUDA, and CUDNN always depends on the system alphafold is installed to. If you look into the pull request, it now advises installing `cudatoolkit==11.2.2`.

Best, Roman

**Comment by Old-Shatterhand** [comment]
I merged the PR today.
