### ISSUE TITLE
Efficient use of multimer mode

### ISSUE THREAD

**Issue by mpgriesh** [kalininalab/alphafold_non_docker#59]
Hi, I am trying to fold heteromeric multimers of one protein against 100s of others. Is there a way to save the structural prediction of the first protein to make this more efficient than submitting #fastas equal to the number of other proteins and refolding the first protein every time?

**Comment by Old-Shatterhand** [comment]
Hi @mpgriesh,

I'm not hundred percent sure if I understand what you try to do. But from what I understand, I think the problem relates more to AlphaFold than to the Docker-free setup. Maybe [this issue](https://github.com/deepmind/alphafold/issues/235) can help you.

Best, Roman

**Comment by mpgriesh** [comment]
Thanks Roman,

Yes, this is an AlphaFold issue. The setup is working well for me. Thanks for your help.
