### ISSUE TITLE
-p <use_precomputed_msas> flag not working

### ISSUE THREAD

**Issue by gerdos** [kalininalab/alphafold_non_docker#62]
I created a multimer prediction and run the very same prediction with the "-p true" flag expecting it to be fast using the precomputed MSAs but the running time is the same.

What am I doing wrong?

**Comment by Old-Shatterhand** [comment]
Hi @gerdos,

for me, this sounds like an issue related to alphafold and not related to the docker-free setup.

Have you checked the [AlphaFold documentation](https://github.com/deepmind/alphafold#running-alphafold) for this? The definition of the `-p` option in the code might help ([Link](https://github.com/deepmind/alphafold/blob/main/run_alphafold.py#L124)).

Best, Roman
