### ISSUE TITLE
Control the number of OpenMM threads

### ISSUE THREAD

**Issue by aozalevsky** [kalininalab/alphafold_non_docker#7]
Since a non-docker setup doesn't have the cgroups limiting capabilities, it would be nice to have finer control over the relaxation step performed with OpenMM. 

The default AF script uses OpenMM with a [CPU platform](http://docs.openmm.org/7.1.0/userguide/library.html#cpu-platform) which by default consumes all CPUs. The behavior can be tuned with the `OPENMM_CPU_THREADS` environment variable which can be setup similar to the GPU selection process. 

For our local version I added following lines:

```
        c)
                openmm_threads=$OPTARG
        ;;
        <...>
      
if [[ "$openmm_threads" ]] ; then
    export OPENMM_CPU_THREADS=${openmm_threads}
fi
  
        
```

**Comment by sanjaysrikakulam** [comment]
Hi @aozalevsky 

I have added OpenMM threads support to the script. Thank you for your suggestion.
